### ISSUE TITLE
johansen parameter modification

### ISSUE THREAD

**Issue by hehpollon** [AnjayGoel/Algorithmic-Trading#2]
Thanks for the great examples!

in
/strategies/mean_reversion/cointegration.py
k_ar_diff parameter should be 1

`jres = coint_johansen(df[[ticker_one, ticker_two]], det_order=0, k_ar_diff=0)`

should be
`jres = coint_johansen(df[[ticker_one, ticker_two]], det_order=0, k_ar_diff=1)`

**Comment by anjay-goel** [comment]
Thanks for pointing out. Fixed in 7564e4d
